<a href="https://colab.research.google.com/github/c-w-m/anlp-tf2/blob/master/chapter1-nlp-essentials/SMS_Spam_Detection-part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Note that this notebook should be uploaded to Google Colab and run there

In [1]:
#%tensorflow_version 2.x
import tensorflow as tf
#from tf.keras.models import Sequential
#from tf.keras.layers import Dense
import os
import io

tf.__version__

'2.4.1'

# Download Data

In [2]:
# Download the zip file
path_to_zip = tf.keras.utils.get_file("smsspamcollection.zip",
                  origin="https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip",
                  extract=True)

# Unzip the file into a folder
!unzip $path_to_zip -d data

204800/203415 [==============================] - 0s 1us/step
Archive:  /root/.keras/datasets/smsspamcollection.zip
  inflating: data/SMSSpamCollection  
  inflating: data/readme             


In [3]:
# optional step - helps if colab gets disconnected
#from google.colab import drive
#drive.mount('/content/drive')

In [4]:
# Test data reading
#lines = io.open('/content/drive/My Drive/colab-data/SMSSpamCollection').read().strip().split('\n')
#lines = io.open('/content/data/SMSSpamCollection').read().strip().split('\n')
lines = io.open('data/SMSSpamCollection').read().strip().split('\n')
lines[0]

'ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

# Pre-Process Data

In [5]:
spam_dataset = []
count = 0
for line in lines:
  label, text = line.split('\t')
  if label.lower().strip() == 'spam':
    spam_dataset.append((1, text.strip()))
    count += 1
  else:
    spam_dataset.append(((0, text.strip())))

print(spam_dataset[0])
print("Spam: ", count)

(0, 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')
Spam:  747


# Data Normalization

In [6]:
import pandas as pd 

In [7]:
df = pd.DataFrame(spam_dataset, columns=['Spam', 'Message'])

In [8]:
import re

# Normalization functions

def message_length(x):
  # returns total number of characters
  return len(x)

def num_capitals(x):
  _, count = re.subn(r'[A-Z]', '', x) # only works in english
  return count

def num_punctuation(x):
  _, count = re.subn(r'\W', '', x)
  return count



In [9]:
df['Capitals'] = df['Message'].apply(num_capitals)
df['Punctuation'] = df['Message'].apply(num_punctuation)
df['Length'] = df['Message'].apply(message_length)

In [10]:
df.describe()

Spam     Capitals  Punctuation       Length
count  5574.000000  5574.000000  5574.000000  5574.000000
mean      0.134015     5.621636    18.942591    80.443488
std       0.340699    11.683233    14.825994    59.841746
min       0.000000     0.000000     0.000000     2.000000
25%       0.000000     1.000000     8.000000    36.000000
50%       0.000000     2.000000    15.000000    61.000000
75%       0.000000     4.000000    27.000000   122.000000
max       1.000000   129.000000   253.000000   910.000000

In [11]:
train=df.sample(frac=0.8,random_state=42) #random state is a seed value
test=df.drop(train.index)

In [12]:
train.describe()

Spam     Capitals  Punctuation       Length
count  4459.000000  4459.000000  4459.000000  4459.000000
mean      0.132765     5.519399    18.886522    80.316439
std       0.339359    11.405424    14.602023    59.346407
min       0.000000     0.000000     0.000000     2.000000
25%       0.000000     1.000000     8.000000    35.000000
50%       0.000000     2.000000    15.000000    61.000000
75%       0.000000     4.000000    27.000000   122.000000
max       1.000000   129.000000   253.000000   910.000000

In [13]:
test.describe()

Spam     Capitals  Punctuation       Length
count  1115.000000  1115.000000  1115.000000  1115.000000
mean      0.139013     6.030493    19.166816    80.951570
std       0.346116    12.731059    15.694599    61.807655
min       0.000000     0.000000     0.000000     2.000000
25%       0.000000     1.000000     8.000000    36.000000
50%       0.000000     2.000000    15.000000    61.000000
75%       0.000000     4.000000    28.000000   123.000000
max       1.000000   127.000000   195.000000   790.000000

# Model Building

In [14]:
# Basic 1-layer neural network model for evaluation
def make_model(input_dims=3, num_units=12):
  model = tf.keras.Sequential()

  # Adds a densely-connected layer with 12 units to the model:
  model.add(tf.keras.layers.Dense(num_units, 
                                  input_dim=input_dims, 
                                  activation='relu'))

  # Add a sigmoid layer with a binary output unit:
  model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', 
                metrics=['accuracy'])
  return model

In [15]:
x_train = train[['Length', 'Punctuation', 'Capitals']]
y_train = train[['Spam']]

x_test = test[['Length', 'Punctuation', 'Capitals']]
y_test = test[['Spam']]

In [16]:
x_train

Length  Punctuation  Capitals
3690      25            4         1
3527     161           48       107
724       40            7         1
3370      69           17         3
468       37            8         1
...      ...          ...       ...
3280     444          114        44
3186      65           14        50
3953      81           23         2
2768      38            8         2
4223      65           14         2

[4459 rows x 3 columns]

In [17]:
model = make_model()

In [18]:
model.fit(x_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
446/446 [==============================] - 4s 2ms/step - loss: 2.1590 - accuracy: 0.6615
Epoch 2/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2808 - accuracy: 0.9261
Epoch 3/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2249 - accuracy: 0.9342
Epoch 4/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2142 - accuracy: 0.9398
Epoch 5/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2055 - accuracy: 0.9374
Epoch 6/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2098 - accuracy: 0.9339
Epoch 7/10
446/446 [==============================] - 1s 2ms/step - loss: 0.2065 - accuracy: 0.9345
Epoch 8/10
446/446 [==============================] - 1s 2ms/step - loss: 0.1901 - accuracy: 0.9410
Epoch 9/10
446/446 [==============================] - 1s 2ms/step - loss: 0.1866 - accuracy: 0.9391
Epoch 10/10
446/446 [==============================] - 1s 2ms/step - loss: 0.1857 - accuracy: 0.9364

In [19]:
model.evaluate(x_test, y_test)

35/35 [==============================] - 0s 2ms/step - loss: 0.2781 - accuracy: 0.8843


[0.27805662155151367, 0.884304940700531]

In [20]:
y_train_pred = model.predict_classes(x_train)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [21]:
# confusion matrix
tf.math.confusion_matrix(tf.constant(y_train.Spam), 
                         y_train_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3837,   30],
       [ 457,  135]], dtype=int32)>

In [22]:
sum(y_train_pred)

array([165], dtype=int32)

In [23]:
y_test_pred = model.predict_classes(x_test)
tf.math.confusion_matrix(tf.constant(y_test.Spam), y_test_pred)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[956,   4],
       [125,  30]], dtype=int32)>

# Tokenization and Stop Word Removal

In [24]:
sentence = 'Go until jurong point, crazy.. Available only in bugis n great world'
sentence.split()

['Go',
 'until',
 'jurong',
 'point,',
 'crazy..',
 'Available',
 'only',
 'in',
 'bugis',
 'n',
 'great',
 'world']

In [25]:
!pip install stanza  # StanfordNLP has become https://github.com/stanfordnlp/stanza/

     |████████████████████████████████| 286kB 7.7MB/s 


In [26]:
import stanza

In [27]:
en = stanza.download('en') 

2021-04-05 02:36:21 INFO: Downloading default packages for language: en (English)...
2021-04-05 02:37:40 INFO: Finished downloading models and saved to /root/stanza_resources.


In [28]:
en = stanza.Pipeline(lang='en')

2021-04-05 02:37:40 INFO: Loading these models for language: en (English):
| Processor | Package   |
-------------------------
| tokenize  | combined  |
| pos       | combined  |
| lemma     | combined  |
| depparse  | combined  |
| sentiment | sstplus   |
| ner       | ontonotes |

2021-04-05 02:37:40 INFO: Use device: gpu
2021-04-05 02:37:40 INFO: Loading: tokenize
2021-04-05 02:37:51 INFO: Loading: pos
2021-04-05 02:37:51 INFO: Loading: lemma
2021-04-05 02:37:51 INFO: Loading: depparse
2021-04-05 02:37:52 INFO: Loading: sentiment
2021-04-05 02:37:52 INFO: Loading: ner
2021-04-05 02:37:53 INFO: Done loading processors!


In [29]:
sentence

'Go until jurong point, crazy.. Available only in bugis n great world'

In [30]:
tokenized = en(sentence)

In [31]:
len(tokenized.sentences)

2

In [32]:
for snt in tokenized.sentences:
  for word in snt.tokens:
    print(word.text)
  print("<End of Sentence>")

Go
until
jurong
point
,
crazy
..
<End of Sentence>
Available
only
in
bugis
n
great
world
<End of Sentence>


## Dependency Parsing Example

In [33]:
en2 = stanza.Pipeline(lang='en')
pr2 = en2("Hari went to school")
for snt in pr2.sentences:
  for word in snt.tokens:
    print(word)
  print("<End of Sentence>")

2021-04-05 02:37:53 INFO: Loading these models for language: en (English):
| Processor | Package   |
-------------------------
| tokenize  | combined  |
| pos       | combined  |
| lemma     | combined  |
| depparse  | combined  |
| sentiment | sstplus   |
| ner       | ontonotes |

2021-04-05 02:37:53 INFO: Use device: gpu
2021-04-05 02:37:53 INFO: Loading: tokenize
2021-04-05 02:37:53 INFO: Loading: pos
2021-04-05 02:37:54 INFO: Loading: lemma
2021-04-05 02:37:54 INFO: Loading: depparse
2021-04-05 02:37:54 INFO: Loading: sentiment
2021-04-05 02:37:55 INFO: Loading: ner
2021-04-05 02:37:55 INFO: Done loading processors!


[
  {
    "id": 1,
    "text": "Hari",
    "lemma": "Hari",
    "upos": "PROPN",
    "xpos": "NNP",
    "feats": "Number=Sing",
    "head": 2,
    "deprel": "nsubj",
    "misc": "start_char=0|end_char=4",
    "ner": "S-PERSON"
  }
]
[
  {
    "id": 2,
    "text": "went",
    "lemma": "go",
    "upos": "VERB",
    "xpos": "VBD",
    "feats": "Mood=Ind|Tense=Past|VerbForm=Fin",
    "head": 0,
    "deprel": "root",
    "misc": "start_char=5|end_char=9",
    "ner": "O"
  }
]
[
  {
    "id": 3,
    "text": "to",
    "lemma": "to",
    "upos": "ADP",
    "xpos": "IN",
    "head": 4,
    "deprel": "case",
    "misc": "start_char=10|end_char=12",
    "ner": "O"
  }
]
[
  {
    "id": 4,
    "text": "school",
    "lemma": "school",
    "upos": "NOUN",
    "xpos": "NN",
    "feats": "Number=Sing",
    "head": 2,
    "deprel": "obl",
    "misc": "start_char=13|end_char=19",
    "ner": "O"
  }
]
<End of Sentence>


## Japanese Tokenization Example

In [34]:
jp = stanza.download('ja') 

2021-04-05 02:37:55 INFO: Downloading default packages for language: ja (Japanese)...


KeyboardInterrupt: ignored

In [ ]:
jp = stanza.Pipeline(lang='ja')

In [ ]:
jp_line = jp("選挙管理委員会")

In [ ]:
for snt in jp_line.sentences:
  for word in snt.tokens:
    print(word.text)

# Adding Word Count Feature 

In [ ]:
def word_counts(x, pipeline=en):
  doc = pipeline(x)
  count = sum( [ len(sentence.tokens) for sentence in doc.sentences] )
  return count


In [ ]:
#en = snlp.Pipeline(lang='en', processors='tokenize')
df['Words'] = df['Message'].apply(word_counts)

In [ ]:
df.describe()

In [ ]:
#train=df.sample(frac=0.8,random_state=42) #random state is a seed value
#test=df.drop(train.index)

train['Words'] = train['Message'].apply(word_counts)
test['Words'] = test['Message'].apply(word_counts)


In [ ]:
x_train = train[['Length', 'Punctuation', 'Capitals', 'Words']]
y_train = train[['Spam']]

x_test = test[['Length', 'Punctuation', 'Capitals' , 'Words']]
y_test = test[['Spam']]

model = make_model(input_dims=4)


In [ ]:
model.fit(x_train, y_train, epochs=10, batch_size=10)

In [ ]:
model.evaluate(x_test, y_test)

## Stop Word Removal

In [ ]:
!pip install stopwordsiso

In [ ]:
import stopwordsiso as stopwords

stopwords.langs()

In [ ]:
sorted(stopwords.stopwords('en'))

In [ ]:
en_sw = stopwords.stopwords('en')

def word_counts(x, pipeline=en):
  doc = pipeline(x)
  count = 0
  for sentence in doc.sentences:
    for token in sentence.tokens:
        if token.text.lower() not in en_sw:
          count += 1
  return count

In [ ]:
train['Words'] = train['Message'].apply(word_counts)
test['Words'] = test['Message'].apply(word_counts)

In [ ]:
x_train = train[['Length', 'Punctuation', 'Capitals', 'Words']]
y_train = train[['Spam']]

x_test = test[['Length', 'Punctuation', 'Capitals' , 'Words']]
y_test = test[['Spam']]

model = make_model(input_dims=4)
#model = make_model(input_dims=3)

model.fit(x_train, y_train, epochs=10, batch_size=10)

## POS Based Features

In [ ]:
en = stanza.Pipeline(lang='en')

txt = "Yo you around? A friend of mine's lookin."
pos = en(txt)

In [ ]:
def print_pos(doc):
    text = ""
    for sentence in doc.sentences:
        for token in sentence.tokens:
            text += token.words[0].text + "/" + \
                    token.words[0].upos + " "
        text += "\n"
    return text

In [ ]:
print(print_pos(pos))

In [ ]:
en_sw = stopwords.stopwords('en')

def word_counts_v3(x, pipeline=en):
  doc = pipeline(x)
  count = 0
  for sentence in doc.sentences:
    for token in sentence.tokens:
        if token.text.lower() not in en_sw and \
        token.words[0].upos not in ['PUNCT', 'SYM']:
          count += 1
  return count

In [ ]:
print(word_counts(txt), word_counts_v3(txt))

In [ ]:
train['Test'] = 0
train.describe()

In [ ]:
def word_counts_v3(x, pipeline=en):
  doc = pipeline(x)
  totals = 0.
  count = 0.
  non_word = 0.
  for sentence in doc.sentences:
    totals += len(sentence.tokens)  # (1)
    for token in sentence.tokens:
        if token.text.lower() not in en_sw:
          if token.words[0].upos not in ['PUNCT', 'SYM']:
            count += 1.
          else:
            non_word += 1.
  non_word = non_word / totals
  return pd.Series([count, non_word], index=['Words_NoPunct', 'Punct'])

In [ ]:
x = train[:10]
x.describe()

In [ ]:
train_tmp = train['Message'].apply(word_counts_v3)
train = pd.concat([train, train_tmp], axis=1)
train.describe()

In [ ]:
test_tmp = test['Message'].apply(word_counts_v3)
test = pd.concat([test, test_tmp], axis=1)
test.describe()

In [ ]:
z = pd.concat([x, train_tmp], axis=1)
z.describe()

In [ ]:
z.loc[z['Spam']==0].describe()

In [ ]:
z.loc[z['Spam']==1].describe()

In [ ]:
aa = [word_counts_v3(y) for y in x['Message']]

In [ ]:
ab = pd.DataFrame(aa)
ab.describe()

# Lemmatization

In [ ]:

text = "Stemming is aimed at reducing vocabulary and aid un-derstanding of" +\
       " morphological processes. This helps people un-derstand the" +\
       " morphology of words and reduce size of corpus."

lemma = en(text)

In [ ]:
lemmas = ""
for sentence in lemma.sentences:
        for token in sentence.tokens:
            lemmas += token.words[0].lemma +"/" + \
                    token.words[0].upos + " "
        lemmas += "\n"

print(lemmas)

# TF-IDF Based Model


In [ ]:
# if not installed already
!pip install sklearn

In [ ]:
corpus = [
          "I like fruits. Fruits like bananas",
          "I love bananas but eat an apple",
          "An apple a day keeps the doctor away"
]


## Count Vectorization

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

vectorizer.get_feature_names()

In [ ]:
X.toarray()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(X.toarray())

In [ ]:
query = vectorizer.transform(["apple and bananas"])

cosine_similarity(X, query)

## TF-IDF Vectorization

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer(smooth_idf=False)
tfidf = transformer.fit_transform(X.toarray())

pd.DataFrame(tfidf.toarray(), 
             columns=vectorizer.get_feature_names())

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

tfidf = TfidfVectorizer(binary=True)
X = tfidf.fit_transform(train['Message']).astype('float32')
X_test = tfidf.transform(test['Message']).astype('float32')

In [ ]:
X.shape

In [ ]:
from keras.utils import np_utils

_, cols = X.shape
model2 = make_model(cols)  # to match tf-idf dimensions
lb = LabelEncoder()
y = lb.fit_transform(y_train)
dummy_y_train = np_utils.to_categorical(y)
model2.fit(X.toarray(), y_train, epochs=10, batch_size=10)

In [ ]:
model2.evaluate(X_test.toarray(), y_test)

In [ ]:
train.loc[train.Spam == 1].describe() 

# Word Vectors

In [ ]:
# memory limit may be exceeded. Try deleting some objects before running this next section
# or copy this section to a different notebook.
!pip install gensim

In [ ]:
from gensim.models.word2vec import Word2Vec
import gensim.downloader as api

In [ ]:
api.info()

In [ ]:
model_w2v = api.load"word2vec-google-news-300")

__deprecated__
```python
model_w2v = api.load"word2vec-google-news-300")
```
__runtime error__
```shell
[=========-----------------------------------------] 18.0% 299.5/1662.8MB downloaded
---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
<ipython-input-135-1bce0bfee7a7> in <module>()
----> 1 model_w2v = api.load("word2vec-google-news-300")

7 frames
/usr/lib/python3.7/ssl.py in read(self, len, buffer)
    927         try:
    928             if buffer is not None:
--> 929                 return self._sslobj.read(len, buffer)
    930             else:
    931                 return self._sslobj.read(len)

ConnectionResetError: [Errno 104] Connection reset by peer
```
__local run__
```shell
/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:252: 

UserWarning: This function is deprecated, use smart_open.open instead. 

See the migration notes for details: 
https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
```

* [RaRe-Technologies/smart_open/README.rst](https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function)

* [Migration Guide](https://github.com/RaRe-Technologies/smart_open/blob/master/MIGRATING_FROM_OLDER_VERSIONS.rst)

__this did NOT work__
* [bhaettasch/gensim_word2vec_demo.py](https://gist.github.com/bhaettasch/d7f4e22e79df3c8b6c20)

__growupboron__ comment on Aug 24, 2020
Since this example this deprecated, I created a [Google Colab demo](https://colab.research.google.com/drive/1aLNhDu1qtQnNIvN5Hhl0UhNBBe84N9S4?usp=sharing) for the same.

In [ ]:
"""
# download and extract the Google News Dataset
!wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=0B7XkCwpI5KDYNlNUTTlSS21pQmM' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=0B7XkCwpI5KDYNlNUTTlSS21pQmM" -O GoogleNews-vectors-negative300.bin.gz && rm -rf /tmp/cookies.txt
!gunzip GoogleNews-vectors-negative300.bin.gz
"""

In [ ]:
"""
import gensim
from gensim import models
from gensim.models import Word2Vec

# Load pretrained model (since intermediate data is not included, the model cannot be refined with additional data)
#model = Word2Vec.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True, norm_only=True) -> Deprecated
model_w2v = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True) #without *norm_only* param
"""

In [ ]:
model_w2v.most_similar("cookies",topn=10)

In [ ]:
model_w2v.doesnt_match(["USA","Canada","India","Tokyo"])

In [ ]:
king = model_w2v['king']
man = model_w2v['man']
woman = model_w2v['woman']

queen = king - man + woman  
model_w2v.similar_by_vector(queen)